
service: practice-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: java17
  region: ${self:custom.region}
  profile: kazitanvir.azad@xxxxxxxxxxxxxxx.com
  stage: dev
  timeout: 10
  memorySize: 128
  environment:
    REGION: ${self:custom.region}
    DYNAMODB_PRACTICETABLE_NAME: ${self:custom.dynamodbPracticeTable}
    DYNAMODB_PRACTICETABLE_PRIMARYKEY: ${self:custom.dynamodbPracticeTablePrimaryKey}
  apiGateway:
    restApiId: xxxxxxxxxx
    restApiRootResourceId: xxxxxxxxxx
  iam:
    role: arn:aws:iam::xxxxxxxxxxxx:role/xxxxxxxx-xxxx





custom:
  region: us-east-1
  dynamodbPracticeTable: xxxxxxxx-xxxxx
  dynamodbPracticeTablePrimaryKey: xxxx_id


# you can add packaging information here
package:
  artifact: target/${self:service}-${self:provider.stage}-1.0.jar
  individually: true
  exclude:
    - README.md
    - .git/**
    - postman
    - .settings/**
    - .classpath
    - .gitignore
    - .project
    - .idea




functions:
  practicetestapi:
    handler: com.serverless.handler.PracticeTestLambda
    memorySize: 512
    timeout: 15
  AddAnimal:
    handler: com.serverless.handler.AddAnimal
    memorySize: 1024
    timeout: 15
  GetAnimalList:
    handler: com.serverless.handler.GetAnimalList
    memorySize: 1024
    timeout: 15
  GetAnimalByName:
    handler: com.serverless.handler.GetAnimalByName
    memorySize: 1024
    timeout: 15
  UpdateAnimalByAttribute:
    handler: com.serverless.handler.UpdateAnimalByAttribute
    memorySize: 1024
    timeout: 15
  UpdateAnimalByFood:
    handler: com.serverless.handler.UpdateAnimalByFood
    memorySize: 1024
    timeout: 15
  DeleteAnimal:
    handler: com.serverless.handler.DeleteAnimal
    memorySize: 1024
    timeout: 15
#    events:
#      - http:
#          path: /api/v1/getanimalbyname
#          method: GET
#          integration: lambda
#          cors: true
#          private: true
# Use this event for api gateway at the starting of development



resources:
  Resources:
    PracticeDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: xxxx_id
            AttributeType: S
        KeySchema:
          - AttributeName: xxxx_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_PRACTICETABLE_NAME}

